[package]
authors = ["Rouven Reuter", "Peter Robinson", "Patrick Simon Nairne"]
description = "A configurable ETL pipeline to convert tables into phenpackets"
edition = "2024"
homepage = "https://robinsongroup.github.io/"
license = "MIT"
name = "pheno_xtrackt"
version = "0.1.0"

[dependencies]
config = { version = "0.15.13", features = ["yaml"] }
polars = "0.50.0"
serde = "1.0.219"
anyhow = "1.0.98"
phenopackets = "0.2.2-post1"