[package]
authors = ["Rouven Reuter", "Peter Robinson", "Patrick Simon Nairne"]
description = "A configurable ETL pipeline to convert tables into phenpackets"
edition = "2024"
homepage = "https://robinsongroup.github.io/"
license = "MIT"
name = "phenoxtrackt"
version = "0.1.0"

[dependencies]
config = "0.15.13"
polars = "0.50.0"
serde = "1.0.219"
anyhow = "1.0.98"
phenopackets = "0.2.2-post1"
validator = { version = "0.20.0", features = ["derive"] }
calamine = "0.30.0"
regex = "1.11.1"
log = "0.4.27"
rust_xlsxwriter = "0.90.0"

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.8"